### ISSUE TITLE
performance problems in Firefox and Safari

### ISSUE THREAD

**Issue by Bortxx** [jquery/PEP#280]
I am binding the 'pointermove' event to a function that simply displays the e.clientY in an element and getting buffering issues. When I move my finger many times fast over the element bound to 'pointermove' the event backs up and values in my display element continue to change after I release my finger telling me that the event can't keep up with my finger move and buffering is occurring.

IE11 and Edge are not exhibiting this problem. Since they support pointer events natively it leads me to believe that the problem is in the PEP library since it is virtually bypassed in IE and Edge. Strangely Chrome is also fast. The speed lag is very prominent in Firefox and to a lesser degree in Safari.

**Comment by patrickhlauke** [comment]
generally, even when listening to `touchmove`, you usually want to do some form of throttling / debouncing with something like https://github.com/m-gagne/limit.js - but in principle, i'm not surprised that the performance (for something that fires potentially 100s of events per second) of native PE would be better than polyfilled PE.

**Comment by dmethvin** [comment]
@Bortxx can you post a simple case that exhibits the problem to jsbin.com or jsfiddle.net? That will make it possible to do profiling and find out where the bottleneck lies.

**Comment by Bortxx** [comment]
patricklauke: yes I understand how a polyfill would perform worse but it is a lot worse and I can't explain why the same code using a different touch library like: [https://github.com/stephband/jquery.event.move/](url) does not exhibit this problem in Firefox and also doesn't explain why PEP performs great in Chrome which doesn't have pointer events like IE and Edge which of course would perform well.

**Comment by patrickhlauke** [comment]
the differences in performance for Chrome probably stem from optimisations that Chrome itself does to touch events dispatching. as @dmethvin said, if you have a link to your code (ideally as a reduced test case) it may be possible to see if there's anything obvious happening there or in PEP

**Comment by Bortxx** [comment]
Did another test and the PointerMove event is occurring only once every 300ms in Firefox when moving finger fast. So the problem is not throttling. Chrome it is raising the same event about every 15ms. Will try to do a jsfiddle example.

**Comment by Bortxx** [comment]
So I tried to do a simplified jsbin example but the problem would not occur with small DOM. So I had to include my entire DOM which is rather large. Took out all non relevant script. This leaves me to believe that the PEP library must be traversing the entire DOM quite frequently for something (Firefox only). 

To test, touch and move your finger up and down. The longer you do this the more apparent it becomes that the events get buffered and a long lag occurs. This problem is only with Firefox on Android. Test with Chrome on Android as comparison to see how fast it should be -- no buffering. Also all browsers on desktop are not exhibiting this problem. I tested with other js touch libraries and no performance problems exist with same code on Firefox so I believe it is something unique with PEP.

http://jsbin.com/nerokayeha/1

**Comment by dmethvin** [comment]
@Bortxx I realized you hadn't stated exactly what device you were using to test. Just as a baseline I used a Nexus 5 with Chrome and am not seeing any long delays but I think you had already established that. It takes about 2ms per update and everything stays up to date. 

I'm also wondering, are you doing heavy DOM updates on pointermove in your real code? The sample code uses `.html()` inside the event handler which seems pretty expensive. It would be better to only do the DOM update once per frame.

![capture](https://cloud.githubusercontent.com/assets/157858/15003269/375d5040-1178-11e6-8c3b-0b85ce84ee04.PNG)

**Comment by Bortxx** [comment]
Actually I am using the Nexus 5 too. But I did mention in my first email that the problem is not in Chrome. Chrome is very fast. It is only Firefox on both my Nexus 5 and my Desktop with 8 cores. Same lag problem on both. Also with other touch frameworks and the exact same DOM and code the speed is not an issue on Firefox. So I am wondering if PEP is doing some expensive DOM scan on every event raise because the larger the DOM the bigger the lag.

**Comment by dmethvin** [comment]
I'm not seeing the problem in desktop Firefox either with that jsbin. The events are handled quickly (1.73ms). Most of the time is spent updating the DOM and repainting, pretty much like Chrome. Can you do a performance trace with Firefox and see how it differs?

![capture](https://cloud.githubusercontent.com/assets/157858/15015124/0ebafa74-11d8-11e6-829d-652a8f382390.PNG)

**Comment by patrickhlauke** [comment]
confirming that on nexus 5, firefox/android is super sluggish (compared to buttery smooth chrome). using webIDE/adb helper i tried my hand at a performance chart - lots of time spent in the "Graphics" target finding/dispatching.

![capture](https://cloud.githubusercontent.com/assets/895831/15015888/42fca55c-1206-11e6-806f-82d605ad108d.PNG)

**Comment by arschmitz** [comment]
Looking at the post from @patrickhlauke the thing that sticks out to me is findTarget https://github.com/jquery/PEP/blob/master/src/targeting.js#L76. which potentially does walk all the way up the dom to the root https://github.com/jquery/PEP/blob/master/src/targeting.js#L66. We do a lot of logic in there based on shadowDom. Since this is not supported in anything except chrome currently seems like we should feature detect here and just set document as root. Cant be sure this is the cause as i have not tested yet but seems like a likely culprit.

**Comment by dmethvin** [comment]
Those results are sort of consistent with even the Chrome ones that show `elementFromPoint` being a large part of the time. To answer that question it needs to have a good layout. So maybe layout is taking a lot of time?  What result do you get with this case that replaces the HTML update with an input update?

http://jsbin.com/xalodojufa/edit?html,output

**Comment by Bortxx** [comment]
I don't think the problem is the jquery.html('') call because with small DOM and same event and thus .html() call frequency the performance is great. The problem only arises with large DOM and in fact the larger the slower the performance. Chrome not affected at all by DOM size. This tells me that PEP is doing some expensive DOM traversal that Firefox is slow at. In my tests I've also cached all my jquery references to make sure my selector traversals are not the problem.

**Comment by dmethvin** [comment]
I can't reproduce on Firefox desktop (46 and 48) at all. On my Nexus 5 I can see the slowness in Firefox using your original example but not on my changed one that avoids injecting new HTML.

**Comment by Bortxx** [comment]
OK lets put aside the desktop for now and focus on Firefox on Nexus 5. Here is a version of the test with small DOM injecting HTML:
http://jsbin.com/gehisoxamo/
No speed issues at all. Now the original test with large DOM still injecting HTML (same exact script):
http://jsbin.com/nerokayeha/
Huge lag issues. Now what is different here? The size of the DOM. What is not different? The HTML injection. Help me understand how the HTML injection is adding the lag when the only difference is the size of the DOM. I contend that PEP is doing something expensive directly related to DOM parsing. Which also explains why the exact same large DOM sample using another touch library (https://github.com/stephband/jquery.event.move/) is not experiencing the problem.

**Comment by dmethvin** [comment]
OK, just give me one more data point. Do you see the lag here? http://jsbin.com/xalodojufa/edit?html,output

**Comment by Bortxx** [comment]
Lag is gone in this one. What did you change?

**Comment by dmethvin** [comment]
Like i said above, I changed `.html()` to an update of an input element. That avoids changing the layout, you're just changing text inside the box. Since you are updating the html *inside* the event handler, that code can run many times in a single frame and each time it may force layout. That's really wasteful, and would be wasteful with any high-frequency event like `mousemove` or `scroll` as well. Yes it's related to DOM size because if the browser sees the need for a full-page layout it's more work. But your code is what forced layout by modifying the DOM inside an event handler, rather than throttling it via `requestAnimationFrame`.

Why isn't it slow in Chrome? Chrome must either deliver fewer events or be better at detecting when the layout needs to be updated to answer the `elementFromPoint` question.

**Comment by Bortxx** [comment]
Unfortunately that sample is not the real world app. And in the real world app that event needs to change the layout. Not through an .html() call (that was just an example) but with a .css() call changing color styles, showing/hiding relevant buttons, and other stuff. 

Chrome does not deliver fewer events, I counted them. So it seems that maybe elementFromPoint is slow in Firefox with large DOM. I don't know enough about the inner workings of PEP nor the need for elementFromPoint use but is there any way to internally do some caching or not use elementFromPoint. Like I said other touch libraries that essentially so the same thing like (https://github.com/stephband/jquery.event.move/) do not have this problem. They have other problems and why I am looking at PEP but not this one.

**Comment by dmethvin** [comment]
Only update the DOM once per frame, using `requestAnimationFrame`. That is good practice in all browsers and will improve performance/battery in all of them. Doing the update in the event handler is wasteful since many of those  updates will never see the screen--they'll be overwritten by later changes in the same frame and the browser will be wasting its efforts.

**Comment by Bortxx** [comment]
I will give that a try and report back if it worked in the real app. Thanks for the advice.

**Comment by dmethvin** [comment]
The MDN page on the resize event has some code examples, https://developer.mozilla.org/en-US/docs/Web/Events/resize

**Comment by scottgonzalez** [comment]
> I don't know enough about the inner workings of PEP nor the need for elementFromPoint use but is there any way to internally do some caching or not use elementFromPoint.

We can't cache values as that would result in incorrect data in the events. As an end user, *you* can cache values and avoid lots of unnecessary work. In the MDN page that @dmethvin linked to, the `running` flag is used to avoid accomplish the same work as caching, by ignoring all subsequent events between frames.

**Comment by Bortxx** [comment]
Thanks guys. Will do.

**Comment by Bortxx** [comment]
Tried the requestAnimationFrame() frame approach and it didn't help at all. Looks like that's not the problem. Chrome still blazing fast and Firefox very very slow. No problems with other touch APIs in Firefox that use the same underlying native calls so the problem must be related with the PEP implementation.

**Comment by scottgonzalez** [comment]
Again, a test case is necessary to review what's happening.

**Comment by Bortxx** [comment]
OK will do a side by side slider. Same JS code on my side, PEP vs another touch API to demonstrate the problem that

**Comment by patrickhlauke** [comment]
If the problem only appears in Firefox, and is due to some API/function call in Firefox being slow, then it needs to be reported/fixed at Mozilla's end, as I don't think there's much wiggle room in the PEP code to try and work around any potential slowness.

**Comment by dmethvin** [comment]
Please do show the code. I'd be really surprised if it made no difference at all. Given the Chrome profile I would even think it should even speed up that case. The magnitude of the performance issue probably is just a Firefox-specific thing given that the MDN page says "the event handler shouldn't execute computationally expensive operations such as DOM modifications" and that is exactly what the code is doing.

**Comment by Bortxx** [comment]
Here is a test link https://www.perecli.com/download/test/test2.htm . I could not get it to work in jsbin.
Tested on Firefox on Nexus 5. Slider on the left uses PEP. Slider on the right uses another touch lib. My JS code is identical for both. Things of note:
- PEP performs horribly without requestAnimationFrame
- With requestAnimationFrame PEP still hangs and hiccups but now its performance is close to the other lib which I don't run through requestAnimationFrame
- In Chrome requestAnimationFrame makes no precivable difference, both libraries perform silky smooth with or without requestAnimationFrame

Don't know what to conclude. I guess requestAnimationFrame only helps PEP a little in Firefox but not enough.

**Comment by scottgonzalez** [comment]
You're still rendering multiple times per frame. The performance improvement you're seeing is from the rendering being back to back and the browser being able to cache some data. Please refer back to the [MDN article](https://developer.mozilla.org/en-US/docs/Web/Events/resize) and see the `running` flag that I mentioned in https://github.com/jquery/PEP/issues/280#issuecomment-216962187.

**Comment by Bortxx** [comment]
Hmm.. The documentation I read states that multiple calls to requestAnimationFrame within the same frame interval are bundled together by the browser and the UI and reflow rendering is only performed once. You could be correct that Firefox does not do this. I might have read this in the Chrome docs. I'll give it a try.

**Comment by scottgonzalez** [comment]
That's exactly in line with what I just said. They are *bundled* together, successive calls are not just ignored. So you are still rendering many times. The reflow rendering happens once because of the internal caching, but you're still performing unnecessary work and that work takes time.

**Comment by Bortxx** [comment]
But when the event comes with some parameters which the rendering depends on, the running flag will actually skip some of those parametered rendering calls causing the UI to possibly be left in an inconsistent state.

The MDN article works because the refresh event has no parameters that the rendering depends on.

**Comment by scottgonzalez** [comment]
> But when the event comes with some parameters which the rendering depends on, the running flag will actually skip some of those parametered rendering calls causing the UI to possibly be left in an inconsistent state.

No it won't. You need to design the code to update the parameters, but not enqueue another rendering. The queued function already uses a closure for the value, so there's no issue with that.

**Comment by scottgonzalez** [comment]
Closing due to inactivity.
